name: Deploy to Netlify

on:

  workflow_dispatch:


env:
  NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      run: |
        npm ci

    - name: Build the React app
      run: |
        npm run build

        
    - name: Create a new Netlify site
      uses: netlify/actions/cli@v2.3.0
      with:
        args: create --new-site --dir=build --auth=$NETLIFY_AUTH_TOKEN
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      id: create_site


    - name: Deploy to Netlify
      uses: netlify/actions/cli@v2.3.0
      with:
        args: deploy --dir=build --prod --auth=$NETLIFY_AUTH_TOKEN --site=$NETLIFY_SITE_ID
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ steps.create_site.outputs.site_id }}

